import React from "react";
import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cabin = Cabin({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${cabin.className} main-background w-full min-h-[100vh]`}
      >
        {children}
      </body>
    </html>
  );
}
